services:
  api:
    container_name: blue-carbon-cost-api
    environment:
      DB_HOST: database
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./shared/config/.env
    command: ["pnpm", "api:dev"]
    networks:
      - 4-growth-docker-network
    depends_on:
      - database

  backoffice:
    container_name: blue-carbon-cost-admin
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: blc
      DB_USERNAME: blue-carbon-cost
      DB_PASSWORD: blue-carbon-cost
      API_URL: http://host.docker.internal:4000
      NODE_ENV: development
      BACKOFFICE_SESSION_COOKIE_NAME: backoffice
      BACKOFFICE_SESSION_COOKIE_SECRET: backoffice_session_secret
    build:
      context: .
      dockerfile: backoffice/Dockerfile
    ports:
      - "1000:1000"
    networks:
      - 4-growth-docker-network
    depends_on:
      - database

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "http://api:4000"
        NEXTAUTH_SECRET: "mysupersecret"
        NEXTAUTH_URL: "http://client:3000/auth/api"
        NEXT_PUBLIC_MAPBOX_API_TOKEN: "${NEXT_PUBLIC_MAPBOX_API_TOKEN}"
    ports:
      - "3000:3000"
    networks:
      - 4-growth-docker-network

  # Used to test the integration between the client, api and backoffice.
  # Some dependencies are disabled as we typically use nginx and database containers only.
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - database
      # - client
      # - api
      # - admin

  database:
    image: postgis/postgis:16-3.4
    container_name: blue-carbon-cost-db
    environment:
      POSTGRES_USER: blue-carbon-cost
      POSTGRES_PASSWORD: blue-carbon-cost
      POSTGRES_DB: blc
    ports:
      - "5433:5432"
    networks:
      - 4-growth-docker-network

  minio:
    image: minio/minio
    container_name: minio-dev
    ports:
      - "9000:9000" # API
      - "9001:9001" # Web UI
    volumes:
      - .tmp/minio-dev:/data
    environment:
      - MINIO_ROOT_USER=testtest
      - MINIO_ROOT_PASSWORD=testtest
    command: server /data --console-address ":9001"

networks:
  4-growth-docker-network:
    driver: bridge
